apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-huwnqszc
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-huwnqszc:262b1ab579194d5e9541f5f4117b0a129db96b11@sha256:4ba1d24f535836dbbad15761ff0dbe175667b47d8f274d983170b6f6ff0c64ce
          name: container-image
